#!/bin/bash
set -e
script_base=$(dirname "$0")
source $script_base/../tools
cd $script_base/../..

load_env

port=${FLOWER_PORT:-5555}
detach=

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -d|--detach)
            detach=-d
            ;;
        -p|--port)
            port=$2
            shift
            ;;
        -h|--help|?)
            if [ "$2" != "quiet" ]; then
                echo "A web-based tool for monitoring and administration Celery"
                echo
                cecho "Usage: run_util $(basename $0) <options>" default bold
                echo
            else
                echo "flower"
                echo "------"
                echo "flower - A web-based tool for monitoring and administration Celery"
            fi
            echo "Options:"
            echo "  -p  --port         Port to bind"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

if [ "$DEV_DOCKER_WORKFLOW" == "none" ]; then
    cecho "This utility requires docker to run. Please review your .env file." red bold
    exit 1
fi

docker-compose run --rm \
    --name flower \
    -p $port:5555 \
    $detach \
    task_worker \
    sh -c "flower -A base_app.celery"
