#!/bin/bash
set -e
script_base=$(dirname "$0")
source $script_base/tools
cd $script_base/..

load_env

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h|--help|?)
            echo "Watch output of a running service."
            echo
            cecho "Usage: $(basename $0) <options> <SERVICE>" default bold
            echo
            echo "Services:"
            echo "$(docker-compose config --services)"
            echo
            echo "Options:"
            echo "  -h  --help          This help message"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"
target=$1

if [ $(can_run_docker $DEV_DOCKER_WORKFLOW $target) ]; then
    docker-compose logs -f $target
else
    cecho "Cannot attach to '$target' while DEV_DOCKER_WORKFLOW set as '$DEV_DOCKER_WORKFLOW'. Please review your .env file." red bold
    exit 1
fi
