#!/bin/bash
set -e
script_base=$(dirname "$0")
source $script_base/tools
cd $script_base/..

load_env

target=app

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -t|--target)
            target=$2
            shift
            ;;
        -h|--help|?)
            echo "Launch an interactive console on the appropriate service."
            echo
            cecho "Usage: $(basename $0) [<CONSOLE TYPE>]" default bold
            echo
            echo "Console Types:"
            echo "  bash           - Bash (Default)"
            echo "  sudo           - Bash as sudo"
            echo "  py    | python - Django Shell Plus w/ IPython"
            echo "  sql   | psql   - PostgreSQL as root"
            echo "  cache | redis  - Redis"
            echo
            echo "Options:"
            echo "  -h  --help          This help message"
            echo "  -t  --target        Choose which service to connect to for `bash` or `sudo` consoles (default: app)"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

if [ "$1" ]; then
    shell=$1
else
    shell="bash"
fi

docker_flags=
docker_required=

case $shell in
    bash)
        cmd=bash
        docker_required=1
        ;;
    sudo)
        cmd=bash
        docker_flags+=" -u root"
        docker_required=1
        ;;
    py|python)
        cmd="./manage.py shell_plus"
        target=app
        ;;
    sql|psql)
        cmd="psql -U postgres"
        target=db
        docker_flags+=" -u root"
        ;;
    cache|redis)
        cmd=redis-cli
        target=cache
        ;;
    *)
        cecho "You must provide a valid shell type. Please see '$(basename $0) --help' for more information." red bold
        exit 1
        ;;
esac

if [ $(can_run_docker $DEV_DOCKER_WORKFLOW $target) ]; then
    docker-compose exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" $docker_flags $target $cmd
elif [ "$docker_required" ]; then
    cecho "Cannot run console '$shell' on target '$target' while DEV_DOCKER_WORKFLOW set as '$DEV_DOCKER_WORKFLOW'. Please review your .env file." red bold
    exit 1
else
    $cmd
fi
