#!/bin/bash
set -e
script_base=$(dirname "$0")
source $script_base/tools
cd $script_base/..

load_env

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h|--help|?)
            echo "Run a specific service in interactive debug mode."
            echo
            cecho "Usage: $(basename $0) <options> [<SERVICE>]" default bold
            echo
            echo "Services:"
            echo "$(docker-compose config --services)"
            echo
            echo "Options:"
            echo "  -h  --help          This help message"
            echo
            echo "Run 'docker-compose up --help' to see more options"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

if [ "$1" ]; then
    service=$1
else
    service=app
fi

if [ $(can_run_docker $DEV_DOCKER_WORKFLOW $service) ]; then
    cecho "Restarting '$service' in interactive debug mode. Kill the process to return to normal." yellow bold
    docker-compose stop $service
    docker-compose run --name base_app_debug-$service --rm --service-ports $service \
        && docker-compose up -d $service
else
    cecho "Since the '$service' service is not managed by Docker, we cannot restart in debug mode." red bold
    cecho "Please start debug mode for this servie manually or review your .env file." red bold
    exit 1
fi
