#!/bin/bash
set -e
script_base=$(dirname "$0")
source $script_base/tools
cd $script_base/..

load_env

if [ $(can_run_docker $DEV_DOCKER_WORKFLOW app) ]; then
    runner="docker-compose run --rm app"
else
    runner=
fi
$runner ./manage.py $@

