#!/bin/bash
set -e
script_base=$(dirname "$0")
source $script_base/tools
cd $script_base/..

load_env

no_input=

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -y|--no-input)
            no_input=1
            ;;
        -h|--help|?)
            echo "Reset environment after a large repository update."
            echo
            cecho "Usage: $(basename $0) <options>" default bold
            echo
            echo "Options:"
            echo "  -y  --no-input      Assume yes for all user input"
            echo "  -h  --help          This help message"
            exit 0
            ;;
        *)
            POSITIONAL+=("$key")
            ;;
    esac
    shift
done
set -- "${POSITIONAL[@]}"

if [ ! "$no_input" ]; then
    cecho "This will delete many files and volumes and may be destructive to work in progress." yellow bold
    read -n1 -r -p "Press 'Y' to continue or any other key to cancel..." key
    echo
    if [ ! "$key" ] || [[ "yY" != *"$key"* ]]; then
        echo
        cecho "Aborting." red
        exit 0
    fi
fi

$script_base/cleanup --no-input

if [ $(can_run_docker $DEV_DOCKER_WORKFLOW app) ]; then
    echo
    cecho "Rebuilding environment..." default bold
    docker-compose build
    $script_base/install py --

else
    echo
    cecho "Installing Python requirements..." default bold
    $script_base/install py --
fi

echo
cecho "Running database migrations..." default bold
$script_base/start -q -d app db
$script_base/migrate
$script_base/stop -q
